config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:index, :destroy]
  resources :lessons
  resources :questions
  namespace :admin do
    root "lessons#index"
    resources :lessons
    resources :users, only: :index
    resources :subjects, only: [:new, :create, :show]
    resources :subjects do
      resources :lessons, only: :show
    end
    resources :questions do
      resources :answers, only: [:new, :create]
    end
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :lessons
  has_many :questions

  validates :name, presence: true, length: {maximum: 100}
  validates :question_number, presence: true,
    numericality:{only_integer: true, greater_than: 1}
  validates :duration, presence: true,
    numericality:{only_integer: true, greater_than: 1}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :logged_in_user, :require_admin
  layout "admin"
  before_action :load_lesson, only: :show
  before_action :load_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.paginate page: params[:page]
  end

  def show
    @lessons = @subject.lessons.order(created_at: :desc)
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t "feature.subjects.create_success"
      redirect_to admin_subjects_path
    else
      render :new
    end
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "feature.subjects.update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "feature.subjects.update_error"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "feature.subjects.delete_success"
    else
      flash[:danger] = t "feature.subjects.delete_error"
    end
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :question_number, :duration
  end

  def load_lesson
    @subject = Subject.find_by id: params[:id]
  end

  def load_subject
    @subject = Subject.find_by id: params[:id]
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <%= render "shared/error_messages", object: @subject %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :question_number %>
  <%= f.text_field :question_number, class: "form-control" %>

  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/subjects/_lesson_field.html.erb
<table class="table table-striped table-hover table-style">
  <thead>
    <th class="th-style"><p><%= t "user.stt" %></p></th>
    <th class="th-style"><p><%= t "user.status" %></p></th>
    <th class="th-style"><p><%= t "user.duration" %></p></th>
    <th class="th-style"><p><%= t "user.question_number" %></p></th>
    <th class="th-style"><p><%= t "user.point" %></p></th>
    <th class="th-style"></th>
  </thead>
  <tbody>
    <% @lessons.each_with_index do |lesson, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td class="td_style"><%= lesson.status %></td>
        <td class="td_style"><%= lesson.subject.duration %></td>
        <td class="td_style"><%= lesson.subject.question_number %></td>
        <% if lesson.checked? %>
          <td class="td_style"><%= lesson.get_point lesson.id %></td>
        <% elsif %>
          <td class="td_style">--</td>
        <% end %>
        <td class="td_style"><%= link_to t("user.edit"), admin_lesson_path(lesson) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/subjects/edit.html.erb
<% provide :title, t("feature.subject") %>
<% provide :button_text, t("feature.create") %>
<div id="courses" class="row">
  <div class="col-md-6">
    <h2><%= t "feature.create" %></h2>
    <%= render "form" %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<div class="row">
  <div class="col-md-10 col-offset-2">
    <h2><%= t "controller.subject.list_subject" %></h2>
    <%= link_to t("feature.subjects.create"), new_admin_subject_path %>
    <table class="table table-striped table-hover">
      <thead>
        <th><%= t "feature.subjects.name" %></th>
        <th><%= t "feature.subjects.question_number" %></th>
        <th><%= t "feature.subjects.duration" %></th>
        <th><%= t "static_pages.questions.update" %></th>
        <th><%= t "static_pages.questions.delete" %></th>
      </thead>
      <tbody>
        <% @subjects.each do |subject| %>
          <tr>
            <td><%= subject.name %></td>
            <td><%= subject.question_number %></td>
            <td><%= subject.duration %></td>
            <td>
              <%= link_to [:edit,:admin, subject],
                class: "btn btn-primary btn-xs" do %>
                <span class="glyphicon glyphicon-eye-open"></span>
                <%= t "static_pages.questions.update" %>
              <% end %>
            </td>
            <td>
              <%= link_to [:admin, subject], method: :delete,
                data: {confirm: t("static_pages.questions.confirm")},
                class: "btn btn-primary btn-xs" do %>
                <span class="glyphicon glyphicon-eye-open"></span>
                <%= t "static_pages.questions.delete" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, t("feature.subject") %>
<% provide :button_text, t("feature.create") %>
<div id="courses" class="row">
  <div class="col-md-6">
    <h2><%= t "feature.create" %></h2>
    <%= render "form" %>
  </div>
</div>

app/views/admin/subjects/show.js.erb
$(".list_lessons").html("<%= escape_javascript(render('lesson_field')) %>");