config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:index, :destroy]
  resources :lessons
  resources :questions
  namespace :admin do
    root "lessons#index"
    resources :lessons
    resources :users, only: :index
    resources :subjects, only: [:new, :create, :show]
    resources :subjects do
      resources :lessons, only: :show
    end
    resources :questions do
      resources :answers, only: [:new, :create]
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.form" %><%= pluralize object.errors.count, t("shared.error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_left_admin.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
  <ul class="nav menu">
    <li>
      <%= link_to admin_lessons_path do %>
        <span class="glyphicon glyphicon-home"></span>
        <%= t "admin.static_pages.admin" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_users_path do %>
        <span class="glyphicon glyphicon-user"></span>
        <%= t "feature.users" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_subjects_path do %>
        <span class="glyphicon glyphicon-list"></span>
        <%= t "feature.subjects.name" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_questions_path do %>
        <span class="glyphicon glyphicon-list"></span>
        <%= t "feature.questions.name" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_lessons_path do %>
        <span class="glyphicon glyphicon-list"></span>
        <%= t "user.lesson.title" %>
      <% end %>
    </li>
  </ul>
</div>