config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:index, :destroy]
  resources :lessons
  resources :questions
  namespace :admin do
    root "lessons#index"
    resources :lessons
    resources :users, only: :index
    resources :subjects, only: [:new, :create, :show]
    resources :subjects do
      resources :lessons, only: :show
    end
    resources :questions do
      resources :answers, only: [:new, :create]
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject
  has_many :results
  has_many :questions, through: :results

  validate :lesson_min, on: :create

  enum status: [:start, :testing, :unchecked, :checked]

  before_create :create_results

  accepts_nested_attributes_for :results

  def change_status_lesson
    if self.start?
      self.status = :testing
      self.save
    end
  end

  def get_point lesson_id
    @point = Answer.is_correct_answers(lesson_id).count
    @question_number = Lesson.find_by(id: lesson_id).subject.question_number
    return @point, @question_number
  end

  private
  def create_results
    self.questions << self.subject.questions.question_random.order("RANDOM()")
      .limit(self.subject.question_number)
  end

  def lesson_min
    if self.subject.questions.size < self.subject.question_number
      errors.add(:base, "oke")
    end
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :logged_in_user, :require_admin
  layout "admin"
  before_action :load_subjects, only: :index
  before_action :load_lesson, only: [:show, :update]

  def index
  end

  def show
    @results = @lesson.results
  end

  def update
    @lesson.status = :checked if params[:commit] == Settings.finish
    if @lesson.update_attributes lesson_params
      flash[:success] = t ".update_lesson_success"
    else
      flash[:danger] =  t ".update_lesson_fail"
    end
    redirect_to admin_lessons_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def load_lesson
    @lesson = Lesson.find_by id: params[:id]
  end

  def lesson_params
    params.require(:lesson).permit :status
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user
  before_action :load_subjects, only: [:index, :show, :create]
  before_action :load_lesson, only: [:show, :update]

  def index
    @lesson = Lesson.new
    @lessons = current_user.lessons.page(params[:page]).per(10)
  end

  def show
    @lesson.change_status_lesson
  end

  def create
    @lesson = Lesson.new lesson_params
    @lesson.user_id = current_user.id
    if @lesson.save
      flash[:success] = t "create_lesson_success"
    else
      # flash[:danger] = "failded" + @lesson.errors.messages[:lesson].to_s
    end
    redirect_to lessons_path
  end

  def update
    @lesson.status = :unchecked if params[:commit] == Settings.finish
    if @lesson.update_attributes lesson_params
      flash[:success] = t "update_lesson_success"
    else
      flash[:danger] =  t "update_lesson_fail"
    end
    redirect_to lessons_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def load_subject
    @subject = Subject.find_by id: params[:id]
  end

  def load_lesson
    @lesson = Lesson.find_by id: params[:id]
  end

  def lesson_params
    params.require(:lesson).permit :subject_id,
      results_attributes: [:id, :answer_id]
  end
end

app/views/lessons/_lesson.html.erb
<div class="col-md-12 col-md-offset-0">
  <%= form_for @lesson, html: {id: "submit-lesson"} do |f| %>
    <ol>
      <%= f.fields_for :results do |result| %>
        <%= render "question", f: result %>
      <% end %>
    </ol>
    <% if @lesson.testing? || @lesson.start? %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= f.submit :save, class: "btn btn-primary btn-submit" %>
          <%= f.submit :finish,
            class: "btn btn-danger btn-submit pull-right finish-lesson" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lessons/index.html.erb
<div class="col-md-12.col-md-offset-0">
  <%= form_for @lesson, html: {class: "form-inline"} do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.collection_select :subject_id, @subjects, :id, :name, {},
      class: "form-control" %>
    <%= f.submit t("user.lesson.create"), class: "btn btn-primary" %>
  <% end %>
  <hr>

  <table class="table table-striped table-hover table-style">
    <thead>
      <th class="th-style"><p><%= t "user.create_at" %></p></th>
      <th class="th-style"><p><%= t "user.subject" %></p></th>
      <th class="th-style"><p><%= t "user.status" %></p></th>
      <th class="th-style"><p><%= t "user.duration" %></p></th>
      <th class="th-style"><p><%= t "user.question_number" %></p></th>
      <th class="th-style"><p><%= t "user.point" %></p></th>
      <th class="th-style"></th>
    </thead>
    <tbody>
      <% @lessons.each do |lesson| %>
        <tr>
          <td class="td_style"><%= lesson.created_at.strftime t "time.type" %></td>
          <td class="td_style"><%= lesson.subject.name %></td>
          <td class="td_style"><%= lesson.status %></td>
          <td class="td_style"><%= lesson.subject.duration %></td>
          <td class="td_style"><%= lesson.subject.question_number %></td>
          <% if lesson.checked? %>
            <td class="td_style"><%= lesson.get_point lesson.id %></td>
          <% elsif %>
            <td class="td_style"> -- </td>
          <% end %>
          <td class="td_style"><%= link_to t("user.start"), lesson_path(lesson) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @lessons %>

app/views/lessons/show.html.erb
<div class="col-md-8 col-md-offset-1">
  <h1 class="text-center" ><%= @lesson.subject.name %></h1>
    <h3 class="text-center">
      <% if @lesson.checked? %>
        <%= @lesson.get_point @lesson.id %>
      <% end %>
    </h3>
  <hr/>
  <%= render "lesson" %>
</div>