config/routes.rb
Rails.application.routes.draw do
  root "lessons#index"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:index, :destroy]
  resources :lessons
  resources :questions
  namespace :admin do
    root "lessons#index"
    resources :lessons
    resources :users, only: :index
    resources :subjects, only: [:new, :create, :show]
    resources :subjects do
      resources :lessons, only: :show
    end
    resources :questions do
      resources :answers, only: [:new, :create]
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("static_pages.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
          <% if current_user.is_admin? %>
            <li><%= link_to t("admin.static_pages.admin"), admin_root_path %></li>
          <% elsif %>
            <li><%= link_to t("static_pages.questions.name"), questions_path %></li>
            <li><%= link_to t("user.lesson.title"), lessons_path %></li>
          <% end %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              "data-toggle": :dropdown do %>
              <%= t "static_pages.account" %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("static_pages.profile"), current_user %></li>
              <li><%= link_to t("static_pages.settings"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("static_pages.logout"), logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static_pages.login"), login_path %></li>
          <li><%= link_to t("static_pages.signup"), new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t("static_pages.title"), root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t "static_pages.account" %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("static_pages.profile"), "#" %></li>
                <li><%= link_to t("static_pages.setting"), "#" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("static_pages.logout"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t("static_pages.login"), login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header_admin" %>
    <div id="wrapper" class="container-fluid text-center">
      <div class="row content">
        <%= render "shared/left_admin" %>
        <div class="col-md-8 text-left col-md-offset-1">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= favicon_link_tag "framgia.png" %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>